module.exports = {
  GET_SLIDER_DATA: "GET_SLIDER_DATA",
  GET_EQUIPMENTS_DATA: "GET_EQUIPMENTS_DATA",
  GET_CLIENTS_DATA: "GET_CLIENTS_DATA",
  GET_PRODUCTS_DATA: "GET_PRODUCTS_DATA",
  SET_LOADER: "SET_LOADER",
  GET_CITY_COUNT: "GET_CITY_COUNT",
  GET_STATE_COUNT: "GET_STATE_COUNT",
  GET_COUNTRY_COUNT: "GET_COUNTRY_COUNT",
  GET_MANUFACTURER_COUNT: "GET_MANUFACTURER_COUNT",
  GET_CONDITION_COUNT: "GET_CONDITION_COUNT",
  GET_LISTINGTYPE_COUNT: "GET_LISTINGTYPE_COUNT",
  GET_CATEGORY_COUNT: "GET_CATEGORY_COUNT",
};
