module.exports = {
  GET_SLIDER_DATA: "GET_SLIDER_DATA",
  GET_EQUIPMENTS_DATA: "GET_EQUIPMENTS_DATA",
  GET_CLIENTS_DATA: "GET_CLIENTS_DATA",
  GET_PRODUCTS_DATA: "GET_PRODUCTS_DATA",
  SET_LOADER: "SET_LOADER",
};
